modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0-or-later"

[[mods]]
modId="thaumcraft"
version="${file.jarVersion}"
displayName="Thaumcraft 6"
authors="Azanor, GrigLog, Community"
credits="Original mod by Azanor; 1.16.5 community port and maintenance by contributors."
displayURL="https://www.curseforge.com/minecraft/mc-mods/thaumcraft"
issueTrackerURL="https://github.com/GrigLog/Thaumcraft-6/issues"
description='''
Thaumcraft introduces the arcane arts to Minecraft. Explore aspects, research, and ancient magic through devices, creatures, and powerful rituals.
'''

[[dependencies.thaumcraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thaumcraft]]
    modId="curios"
    mandatory=false
    versionRange="[1.16.5-4.0.5.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.thaumcraft]]
    modId="jei"
    mandatory=false
    versionRange="[7.7.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.thaumcraft]]
    modId="jade"
    mandatory=false
    versionRange="[2.8.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.thaumcraft]]
    modId="wthit"
    mandatory=false
    versionRange="[2.10.0,)"
    ordering="NONE"
    side="CLIENT"